remote_theme: cthulhu-oidc/jekyll-theme
google_analytics:

markdown: kramdown
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /documentation/:name

organization:
  url: https://github.com/cthulhu-oidc"
  twitter: https://twitter.com/cthulhu_oidc_js

package:
  name: '@cthulhu/core'
  description: Fast and low overhead oidc provider
  url: https://www.cthulhu-oidc.dev
  repository:
    url: https://github.com/cthulhu-oidc/core
  license: MIT
